MACHINE_ID = "M001"
MACHINE_TYPE = "Industrial Motor"

MAX_CYCLES = 10000

BASE_TEMPERATURE = 50.0
BASE_VIBRATION = 0.8
BASE_CURRENT = 7.5
BASE_PRESSURE = 5.0
BASE_RPM = 1500.0

SIMULATION_INTERVAL = 0.1

MQTT_BROKER = "localhost"
MQTT_PORT = 1883
MQTT_TOPIC = "factory/line1/M001/sensors"

CSV_FILE = "data/machine_data.csv"